colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "hero"
  homepageImage = ""
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  sharingLinks = ["twitter", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  groupByYear = true

[taxonomy]
  showTermCount = true
